locale = "fr"
label = "Français"
weight = 1
title = "Orchestre Symphonique du Hainaut"

[params]
  displayName = "Français"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  timeFormat = "15H04"
  # logo = "img/osh_logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Orchestre Symphonique du Hainaut"
  # image = "img/logo/logo-round.png"
  image = "img/osh_logo.png"
  text_image = "img/logo/osh-txt.png"
  headline = ""
  bio = ""
  email = "orchestre-symphonique-du-hainaut@outlook.fr"
  links = [
    { email = "mailto:orchestre-symphonique-du-hainaut@outlook.fr" },
    { instagram = "https://www.instagram.com/osh_officiel/" },
    # { link = "https://link-to-some-website.com/" },
    # { facebook = "https://facebook.com/username" },
    # { github = "https://github.com/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { twitter = "https://twitter.com/username" },
    # { x-twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
   ]
